#!/usr/bin/env python3
"""
Lala Panel Setup Utility
Creates initial admin user and performs basic setup tasks
"""

import os
import sys
import getpass
from pathlib import Path

# Add current directory to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from database import Database
from werkzeug.security import generate_password_hash
import secrets

def print_banner():
    """Print setup banner"""
    print("""
╔═══════════════════════════════════════════╗
║        Lala Panel Setup Utility           ║
║   Lightweight Hosting Control Panel       ║
╚═══════════════════════════════════════════╝
    """)

def setup_database():
    """Initialize database"""
    config_dir = os.environ.get('CONFIG_DIR', '/etc/lalapanel')
    os.makedirs(config_dir, exist_ok=True)
    
    db_path = os.path.join(config_dir, 'lalapanel.db')
    print(f"[+] Initializing database at {db_path}")
    
    db = Database(db_path)
    print("[✓] Database initialized")
    
    return db

def create_admin_user(db):
    """Create admin user"""
    print("\n[*] Creating admin user")
    print("-" * 45)
    
    # Get username
    username = input("Enter admin username [admin]: ").strip()
    if not username:
        username = "admin"
    
    # Check if user already exists
    existing_user = db.get_user(username)
    if existing_user:
        print(f"[!] User '{username}' already exists")
        overwrite = input("Do you want to reset the password? (yes/no): ").strip().lower()
        if overwrite != 'yes':
            print("[!] Skipping user creation")
            return
    
    # Get password
    while True:
        password = getpass.getpass("Enter admin password: ")
        if len(password) < 8:
            print("[!] Password must be at least 8 characters long")
            continue
        
        password_confirm = getpass.getpass("Confirm admin password: ")
        if password != password_confirm:
            print("[!] Passwords do not match. Please try again.")
            continue
        
        break
    
    # Create or update user
    password_hash = generate_password_hash(password)
    
    if existing_user:
        # Update existing user's password
        with db.get_connection() as conn:
            cursor = conn.cursor()
            cursor.execute(
                'UPDATE users SET password_hash = ? WHERE username = ?',
                (password_hash, username)
            )
        print(f"[✓] Password updated for user '{username}'")
    else:
        db.create_user(username, password_hash)
        print(f"[✓] Admin user '{username}' created successfully")

def create_env_file():
    """Create .env file with configuration"""
    print("\n[*] Creating environment configuration")
    print("-" * 45)
    
    install_dir = os.environ.get('INSTALL_DIR', '/opt/lalapanel')
    env_path = os.path.join(install_dir, '.env')
    
    if os.path.exists(env_path):
        print(f"[!] Environment file already exists at {env_path}")
        overwrite = input("Do you want to overwrite it? (yes/no): ").strip().lower()
        if overwrite != 'yes':
            print("[!] Skipping environment file creation")
            return
    
    # Generate secret key
    secret_key = secrets.token_hex(32)
    
    # Get MariaDB root password
    mariadb_password = getpass.getpass("Enter MariaDB root password (press Enter to skip): ")
    
    # Get Let's Encrypt email
    letsencrypt_email = input("Enter email for Let's Encrypt (press Enter to skip): ").strip()
    
    # Create .env file
    env_content = f"""# Lala Panel Configuration
# Generated by setup utility

# Flask Settings
SECRET_KEY={secret_key}
FLASK_ENV=production

# Database Settings
MARIADB_ROOT_PASSWORD={mariadb_password}
MARIADB_HOST=localhost
MARIADB_PORT=3306

# SSL Settings
LETSENCRYPT_EMAIL={letsencrypt_email or 'admin@localhost'}

# Panel Settings
PANEL_PORT=8080
PANEL_HOST=0.0.0.0
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    os.chmod(env_path, 0o600)
    print(f"[✓] Environment file created at {env_path}")

def check_directories():
    """Check and create required directories"""
    print("\n[*] Checking required directories")
    print("-" * 45)
    
    directories = {
        '/var/www': 'Sites directory',
        '/var/log/lalapanel': 'Logs directory',
        '/etc/lalapanel': 'Configuration directory',
    }
    
    for directory, description in directories.items():
        if os.path.exists(directory):
            print(f"[✓] {description}: {directory}")
        else:
            try:
                os.makedirs(directory, exist_ok=True)
                print(f"[+] Created {description}: {directory}")
            except PermissionError:
                print(f"[!] Cannot create {directory} - permission denied")

def show_next_steps():
    """Show next steps after setup"""
    print("\n" + "=" * 45)
    print("Setup completed successfully!")
    print("=" * 45)
    print("\nNext steps:")
    print("1. Install and configure PHP-FPM for each PHP version")
    print("2. Configure Nginx and ensure it's running")
    print("3. Start the panel service:")
    print("   sudo systemctl start lalapanel")
    print("4. Access the panel at http://YOUR_SERVER_IP:8080")
    print("\nFor more information, see README.md and CONFIGURATION.md")
    print()

def main():
    """Main setup function"""
    print_banner()
    
    # Check if running as root
    if os.geteuid() != 0:
        print("[!] Warning: Not running as root. Some operations may fail.")
        print("    It's recommended to run this script with sudo.")
        print()
    
    try:
        # Check directories
        check_directories()
        
        # Setup database
        db = setup_database()
        
        # Create admin user
        create_admin_user(db)
        
        # Create environment file
        create_env_file()
        
        # Show next steps
        show_next_steps()
        
    except KeyboardInterrupt:
        print("\n\n[!] Setup interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n[!] Error during setup: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == '__main__':
    main()
